### ISSUE TITLE
Handbrake is not displayed

### ISSUE THREAD

**Issue by SkyBerlin** [pre-martin/StreamDeckSimHubPlugin#72]
Game: https://store.steampowered.com/app/491540/The_Bus/

Problem: SimHub proberty "dcp.gd.Handbrake", possible values are 0 or 100. Does not work. Also with expressions like `dcp.gd.Handbrake!=0` or `dcp.gd.Handbrake==0`.

(Ignition, Engine and TurnIndicator works fine)

**Comment by pre-martin** [comment]
Could you please record a short session in SimHub, in which you are toggling the handbrake in your simulation? And then attach the replay (3 files in subfolder in `C:\Program Files (x86)\SimHub\Replays`) to this issue?

**Comment by SkyBerlin** [comment]
Sure, I hope it's helpful.
[TMLTheBus.zip](https://github.com/pre-martin/StreamDeckSimHubPlugin/files/11276966/TMLTheBus.zip)

**Comment by pre-martin** [comment]
Thank you for the replay. The property `dcp.gd.Handbrake` works for me - just like that. See the attached video.

I think that we can exclude typos in the property name (also lowercase/uppercase) as a source for the problem, because you wrote the name correctly in the issue description above. Can you ensure, that there are no trailing or leading spaces in the input field?

Can you send me some logs? Switch to a different page or profile in Stream Deck, than back to the page where you are using the button for the handbrake. Then start the replay (one loop is enough). After the replay has finished, please send me the following two logs:

* C:\Program Files (x86)\SimHub\Logs\PropertyServer.log
* C:\Users\\[yourname]\AppData\Roaming\Elgato\StreamDeck\Plugins\net.planetrenner.simhub.sdPlugin\StreamDeckSimHub.log

Only the last few lines are relevant. They should look something this:
```
2023-04-19 22:36:12,472 DEBUG [54             ] ins.PropertyServer.Comm.Client [cid:3     ] Received from client: subscribe dcp.gd.Handbrake
2023-04-19 22:36:12,473 DEBUG [54             ] rver.Property.PropertyAccessor [cid:3     ] Creating property instance for property dcp.gd.Handbrake in StatusDataBase
2023-04-19 22:36:12,474 INFO  [54             ] ertyServer.SubscriptionManager [cid:3     ] Created new property dcp.gd.Handbrake
```
and
```
2023-04-19 22:36:12.4732 INFO  [163] ub.Plugin.Actions.HotkeyAction OnWillAppear: Hotkey: , Modifier: ---, SimHubControl: , SimHubProperty: dcp.gd.Handbrake, TitleSimHubProperty: , TitleFormat:  
2023-04-19 22:36:12.4732 INFO  [163] Plugin.SimHub.SimHubConnection Sending subscribe for dcp.gd.Handbrake 
```

https://user-images.githubusercontent.com/5703553/233195209-ddabc58c-1236-4a21-afc4-aad0ba7b0882.mp4

**Comment by SkyBerlin** [comment]
It works! You are the best, thank you very much! :-) I used "hotkey 4-state" and not the "hotkey" as you showed in the video. With hotkey it works. Is it then also possible to display the door control and stop request? Unfortunately I can't find a name for them in SimHub. Is it possible to find them through the record function?

**Comment by pre-martin** [comment]
I can try it. Please create a new ticket and upload the replay. In the comments you can write about when you trigger which function.
