### ISSUE TITLE
The Bus Replay

### ISSUE THREAD

**Issue by SkyBerlin** [pre-martin/StreamDeckSimHubPlugin#73]
Hi Martin, here (https://rapidgator.net/file/77a756e390ac000287d43f6efc4c1473/TMLTheBus.7z.html) is the replay of The Bus in SimHub. I have set bookmarks in the replay with description of the actions. I hope it works. Please ask me if you need any more data or specific information. I can forward them to the game developer and provide you with the answers.

Here are maybe some interesting information about the Telemetry Interface: https://www.tml-studios.de/forum/index.php?thread/2577-telemetry-interface-beta/&pageNo=1

**Comment by pre-martin** [comment]
When searching for properties in SimHub under "Available Properties", be sure to tick the option "Show game specific properties (rawdata)". I found the following:

**Stop Brake**
Property: DataCorePlugin.GameRawData.Vehicle.Brake
Values: Jump between 0.4 and 0.8
Posssible expression: DataCorePlugin.GameRawData.Vehicle.Brake>0.5


**Doors** :-(
I only found `DataCorePlugin.GameRawData.Vehicle.PassengerDoorsOpen`, which is one single boolean field for all doors together.


**Driver light** :-(


**Interior light** :-(


**Exterior lights**
Properties:
- DataCorePlugin.GameRawData.Vehicle.DashboardLight
- DataCorePlugin.GameRawData.Vehicle.MainLight
- DataCorePlugin.GameRawData.Vehicle.ParkingLight
- DataCorePlugin.GameRawData.Vehicle.Headlight
- DataCorePlugin.GameRawData.Vehicle.TravellerLight
- DataCorePlugin.GameRawData.Vehicle.RearFogLight
- DataCorePlugin.GameRawData.Vehicle.FogLight
- 
Values: "True" and "False"
Possible expression: DataCorePlugin.GameRawData.Vehicle.MainLight==True

**Wipers**
Property: DataCorePlugin.GameRawData.Vehicle.WiperLevel
Values: 0, 1, 2, 3
Could be solved with the "Hotkey 4-state" by just entering the property name without any expression. Two caveats:
* The Hotkey 4-state is a very ugly button because it cannot be customized. Stream Deck API does not offer full access to buttons with more than two states.
* At the moment, my Stream Deck plugin has a problem with this specific property and the way, how it holds the data. I have to release a new version of the plugin, so that you can use the Hotkey 4-state with the "Bus" wipers.


I also checked the internal data structure of the game and searched for properties, which are not mapped and exposed by SimHub. Unfortunately, I found nothing for Driver Light and Interior Lights.

**Comment by SkyBerlin** [comment]
Thanks for your help, Martin! It works. And now I know how to test it.

For the other things like the doors I guess it needs "json". The game developer said with the telemetry everything can be read and displayed.

There is a developer tool for Stream Deck called "Api Request" (https://github.com/mjbnz/streamdeck-api-request). Maybe you can integrate something like that in your plugin in the future. However, I have no idea how this plugin works and what/how must be entered in Request Headers and Request Body. Your plugin is more user friendly. :-)

![image](https://user-images.githubusercontent.com/131241798/233487823-9a68c08c-c808-435e-a9b1-add9dc33616d.png)

**Comment by pre-martin** [comment]
Open http://localhost:37337/Vehicles/Current with your browser and copy&paste the result into this ticket. you should receive a JSON structure in the browser (lots of elements within curly braces).

**Comment by SkyBerlin** [comment]
Thanks, Martin! I have the JSON file. And now?
[Current JSON.zip](https://github.com/pre-martin/StreamDeckSimHubPlugin/files/11300397/Current.JSON.zip)

**Comment by pre-martin** [comment]
In the JSON file, there are only the following lights:

* DaytimeLight
* ParkingLight
* Headlight
* TravellerLight
* FogLight
* RearFogLight
* MainLight
* DashboardLight
* WarningLights

All of them are read by SimHub. The Driver Lights and Interior Lights do not exist in the JSON data.

The state of the four doors is already included in the JSON file, but SimHub does not read this data.

So your way would be

1. Ask the developer of The Bus to also include Driver Lights and Interior Lights into the JSON data
2. Ask Whotever (https://github.com/SHWotever - the developer of SimHub) to include this new data for the lights, and also the already existing "Doors" data, into SimHub.

**Comment by pre-martin** [comment]
I will take a look at this API Request plugin, so that you could map the doors.

**Comment by SkyBerlin** [comment]
I see, thanks for your help! :-)

**Comment by pre-martin** [comment]
Not really satisfying, but you could give it a try:

Use the plugin API Ninja from https://barraider.com/. It looks more stable, more logical and better maintained to me than "API Request".

The JSON data contains data about the doors like follows:

```
    "Doors": [
        {
            "Name": "Door Fourth",
            "Open": "false",
            "Progress": "0.0",
            "Opened": "false"
        },
        {
            "Name": "Door Third",
            "Open": "false",
            "Progress": "0.0",
            "Opened": "false"
        },
        {
            "Name": "Door Second",
            "Open": "false",
            "Progress": "0.0",
            "Opened": "false"
        },
        {
            "Name": "Door Front",
            "Open": "true",
            "Progress": "1.0",
            "Opened": "true"
        }
    ],
```

Unfortunately, you do not know, which door is at which position in the array. With some luck, it will always be in reversed order like above (e.g. for buses with 6 doors). If they are in random order, you are out of options.

To map the state of the door "Door Fourth" (the first door in the array) to a button, scroll all the way down in the Property Inspector and use "Import Settings" to import the file "fourth.ninja" (you have to extract it from the zip file). This will give you some basic values, which you have to adapt.

[fourth.zip](https://github.com/pre-martin/StreamDeckSimHubPlugin/files/11301127/fourth.zip)

The relevant part of the config is `$.Doors[0].Opened`. This is the state of the first door in the array. The next door would be `$.Doors[1].Opened`. You then check this value against `true`. If this is the case, the "matched" image will be displayed (I've chosen a green one), if not the "unmatched" image will be shown (I took a red one). You have to adjust both images.

As mentioned above, unless the doors are always in the same order, you have no idea which door will be on which position in the array. It would be cool to have a plugin where you could use one information from the response as a title and another information for the image. Then you could use `$.Doors[0].Name` for the title and `$.Doors[0].Opened` for the image. Could be a feature request for BarRaider.

I am closing this issue now, because we get a little bit out of scope :-)
