### ISSUE TITLE
BassShaker Global Gain value

### ISSUE THREAD

**Issue by olavopeixoto** [pre-martin/StreamDeckSimHubPlugin#94]
Is there a way to get the current global gain value and its mute state for the current shakeit profile?
I am only able to read values and states from independent effects or a group.

![image](https://github.com/pre-martin/StreamDeckSimHubPlugin/assets/7496076/6fc633c6-fd8f-419b-9fdf-2dc513e048ef)

**Comment by pre-martin** [comment]
* Property for Title: `ShakeITBSV3Plugin.GlobalGain` (optionally with format `{:F0}%`)
* On the top of your screenshot there are the tabs "Effects Profile", "Sound Output" and "Controls". Change to "Controls".
* Create two buttons in StreamDeck:
  * Enter something like `SibGlobalGainDec` in the field "SimHub Control" of the first button
  * Something like `SibGlobalGainInc` in the same field of the second button
* Back in SimHub on the tab "Controls"
  * Press "Change" on "Increase overall gain". The usual "Pick a control" dialog of SimHub will open. Now press the second button from above
  * Same for "Decrease overall gain" with the first Stream Deck button from above

Of course you can map "Mute" the same way. If you have a Stream Deck + you can put all three of them on the same dial-

**Comment by olavopeixoto** [comment]
Thank you. It worked great.
I just don't know the property for the mute state. How do I find out those property names?

![image](https://github.com/pre-martin/StreamDeckSimHubPlugin/assets/7496076/aab4725d-5003-41bf-9429-931837c752a4)

**Comment by pre-martin** [comment]
I am surprised myself that this property does not exist.

All available properties are listed in SimHub on the page "Available properties", grouped by plugin.

If you filter by "gain", you will find `ShakeITBSV3Plugin.GlobalGain` very quickly. And if you clear the filter and scroll to the section "ShakeITBSV3Plugin" (that's the name for "Bass Shakers V3" - the internal name of ShakeIt Bass), you will find all properties from ShakeIt Bass. There you will see, that there is only one property: Gain, but no mute state.

This is a bit strange, because I think I've seen "Mute" already.

**Comment by pre-martin** [comment]
I had remembered that wrong. I did not mute the whole effect globally, but I created a single parent effect group, which holds all my other effects and groups. The mute state of this parent group can easily be displayed on the Stream Deck.

**Comment by pre-martin** [comment]
![grafik](https://github.com/pre-martin/StreamDeckSimHubPlugin/assets/5703553/eb969289-1ebe-47d8-ae78-ca611aa51aa1)
